[project]
name = 'decentralized-asteroid-mining-investment-platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mining-shares]
path = 'contracts/mining-shares.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-allocator]
path = 'contracts/resource-allocator.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
